use helper;
my $month = read_month();
  log0 "loading data...\n";
create_db("tmp/temp.sqlt");
load_dbf("in/Z2MPZ.dbf", "Z2MPZ", ["ID_KEY", "KFK"]);
load_dbf("in/z43MPS.dbf", "Z43MPS", ["ID_KEY", "KFK"]);
load_dbf("in/W2532${month}Z2M_1.dbf", "WM_1", ["KOD", "ID_KEY"]);
load_dbf("out/W2532${month}Z2M_3.dbf", "out", ["KOD", "ID_KEY"]);
  log0 "loaded dbfs...\n";
load_csv("kod_keys.csv", "kod_keys", ["KOD", "ID_KEY"]);
load_csv("tmp/6325sf.csv", "6325sf", ["KOD"]);
load_csv("tmp/6325zf.csv", "6325zf", ["KOD"]);
  log0 "data loaded, processing...\n";
exec_sql_file("autozvit.sql");
  log0 "processing done, exporting data...\n";
update_dbf("out/W2532${month}Z2M_3.dbf", "out", ["N1", "N2", "N3", "N4", "N6"]);
  log0 "export done, everything is OK.\n";
#append_report("sample report", "out", "report.txt");
