DROP VIEW IF EXISTS `ostat_3142`;
DROP VIEW IF EXISTS `ostat_3152`;
CREATE VIEW `ostat_3142` AS
SELECT `SCET`, SUMA/100., IFNULL(`CR_VALUE`,0) AS `CR_VALUE`, `SUMA`/100.-IFNULL(`CR_VALUE`,0) AS `SUMA-CR_VALUE`
	FROM `ostat`
	LEFT JOIN `sal_3142` ON `ACCOUNT` = `SCET`
	WHERE `SCET` LIKE "3142%" AND `SUMA`-ROUND(IFNULL(`CR_VALUE`,0)*100) != 0;

DROP VIEW IF EXISTS `ostat_3152`;
CREATE VIEW `ostat_3152` AS
SELECT `SCET`, SUMA/100., IFNULL(`CR_VALUE`,0) AS `CR_VALUE`, `SUMA`/100.-IFNULL(`CR_VALUE`,0) AS `SUMA-CR_VALUE`
	FROM `ostat`
	LEFT JOIN `sal_3152` ON `ACCOUNT` = `SCET`
	WHERE `SCET` LIKE "3152%" AND `SUMA`-ROUND(IFNULL(`CR_VALUE`,0)*100) != 0;